schema_version = "1.0.0"
id = "export_me"
version = "2.0.0"
name = "Export ME"
tagline = "Game FBX Exporter by the Metric Empire Studio"
maintainer = "Victor Chedeville <victor.ched@gmail.com>"
type = "add-on"
website = "https://github.com/metric-empire/export-me"
tags = ["Import-Export", "Game Engine", "Pipeline"]
blender_version_min = "5.0.0"
platforms = ["windows-x64"]
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 Metric Empire"]

[permissions]
files = "Import/export FBX from/to disk"

[build]
paths_exclude_pattern = ["__pycache__/", "/.git/", "/*.zip"]
